# Generated by Django 5.2.5 on 2025-08-11 20:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Nombre técnico de la aplicación (sin espacios, ej: sistema_ventas)', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre debe empezar con letra minúscula, solo letras, números y guiones bajos', regex='^[a-z][a-z0-9_]*$')])),
                ('display_name', models.CharField(help_text='Nombre visible de la aplicación (ej: Sistema de Ventas)', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(help_text='Dominio completo (ej: ventas.miempresa.com)', max_length=255, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Subdomain solo si aplica', max_length=100)),
                ('port', models.IntegerField(default=8000, help_text='Puerto para el servidor de desarrollo', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ('db_engine', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite3', 'SQLite3')], default='postgresql', max_length=20)),
                ('db_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Nombre de BD: solo minúsculas, números y guiones bajos', regex='^[a-z][a-z0-9_]*$')])),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=255)),
                ('db_host', models.CharField(default='localhost', max_length=255)),
                ('db_port', models.IntegerField(default=5432)),
                ('base_path', models.CharField(help_text='Ruta base donde se instalará (ej: /home/usuario/apps/)', max_length=500)),
                ('virtualenv_path', models.CharField(blank=True, help_text='Ruta del entorno virtual (se genera automáticamente si está vacío)', max_length=500)),
                ('django_secret_key', models.CharField(blank=True, help_text='Se genera automáticamente si está vacío', max_length=255)),
                ('django_debug', models.BooleanField(default=True)),
                ('django_allowed_hosts', models.TextField(default='*', help_text='Hosts permitidos separados por comas')),
                ('status', models.CharField(choices=[('draft', 'En Diseño'), ('generating', 'Generando'), ('generated', 'Generada'), ('installing', 'Instalando'), ('deployed', 'Desplegada'), ('error', 'Error'), ('maintenance', 'Mantenimiento')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('python_version', models.CharField(default='3.11', help_text='Versión de Python a usar', max_length=20)),
                ('django_version', models.CharField(default='5.0', help_text='Versión de Django a instalar', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'db_table': 'app_generator_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('install', 'Instalación'), ('update', 'Actualización'), ('migration', 'Migración'), ('restart', 'Reinicio'), ('backup', 'Respaldo'), ('error', 'Error')], max_length=20)),
                ('command', models.TextField(help_text='Comando ejecutado')),
                ('output', models.TextField(blank=True, help_text='Salida del comando')),
                ('error_output', models.TextField(blank=True, help_text='Errores si los hay')),
                ('success', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_logs', to='sapy.application')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_generator_deployment_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, help_text='Versión específica o dejar vacío para la última', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='sapy.application')),
            ],
            options={
                'db_table': 'app_generator_dependencies',
                'ordering': ['package_name'],
                'unique_together': {('application', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('is_secret', models.BooleanField(default=False, help_text='Marcar si contiene información sensible')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_vars', to='sapy.application')),
            ],
            options={
                'db_table': 'app_generator_environment',
                'ordering': ['key'],
                'unique_together': {('application', 'key')},
            },
        ),
    ]
