# Generated by Django 5.2.5 on 2025-08-12 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre técnico de la tabla en la BD (ej: productos)', max_length=100)),
                ('alias', models.CharField(help_text='Nombre amigable/alias (ej: Productos)', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('schema_name', models.CharField(blank=True, help_text='Nombre del esquema (opcional, ej: public)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_tables', to='sapy.application')),
            ],
            options={
                'verbose_name': 'Tabla BD',
                'verbose_name_plural': 'Tablas BD',
                'db_table': 'app_generator_db_tables',
                'ordering': ['application__name', 'name'],
                'unique_together': {('application', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DbColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la columna (ej: id, nombre, id_familias)', max_length=100)),
                ('data_type', models.CharField(choices=[('integer', 'INTEGER'), ('bigint', 'BIGINT'), ('smallint', 'SMALLINT'), ('serial', 'SERIAL'), ('bigserial', 'BIGSERIAL'), ('varchar', 'VARCHAR'), ('text', 'TEXT'), ('boolean', 'BOOLEAN'), ('date', 'DATE'), ('timestamp', 'TIMESTAMP'), ('numeric', 'NUMERIC')], help_text='Tipo de dato SQL', max_length=20)),
                ('length', models.PositiveIntegerField(blank=True, help_text='Longitud (solo aplica a VARCHAR)', null=True)),
                ('numeric_precision', models.PositiveIntegerField(blank=True, help_text='Precisión (solo NUMERIC)', null=True)),
                ('numeric_scale', models.PositiveIntegerField(blank=True, help_text='Escala (solo NUMERIC)', null=True)),
                ('is_nullable', models.BooleanField(default=True)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_index', models.BooleanField(default=False)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_auto_increment', models.BooleanField(default=False, help_text='Solo aplica a tipos serial o PK integer')),
                ('default_value', models.CharField(blank=True, help_text='Valor por defecto (literal SQL)', max_length=255)),
                ('position', models.PositiveIntegerField(default=0, help_text='Orden de la columna (0..N)')),
                ('on_delete', models.CharField(choices=[('CASCADE', 'CASCADE'), ('RESTRICT', 'RESTRICT'), ('SET NULL', 'SET NULL'), ('NO ACTION', 'NO ACTION')], default='CASCADE', help_text='Comportamiento ON DELETE para la FK', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('references_table', models.ForeignKey(blank=True, help_text='Tabla de referencia si es FK', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by_columns', to='sapy.dbtable')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='sapy.dbtable')),
            ],
            options={
                'verbose_name': 'Columna BD',
                'verbose_name_plural': 'Columnas BD',
                'db_table': 'app_generator_db_columns',
                'ordering': ['table__name', 'position', 'name'],
                'unique_together': {('table', 'name')},
            },
        ),
    ]
