# Generated by Django 5.2.5 on 2025-08-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0002_dbtable_dbcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbColumnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('integer', 'INTEGER'), ('bigint', 'BIGINT'), ('smallint', 'SMALLINT'), ('serial', 'SERIAL'), ('bigserial', 'BIGSERIAL'), ('varchar', 'VARCHAR'), ('text', 'TEXT'), ('boolean', 'BOOLEAN'), ('date', 'DATE'), ('timestamp', 'TIMESTAMP'), ('numeric', 'NUMERIC')], max_length=20)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('numeric_precision', models.PositiveIntegerField(blank=True, null=True)),
                ('numeric_scale', models.PositiveIntegerField(blank=True, null=True)),
                ('is_nullable', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_index', models.BooleanField(default=False)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_auto_increment', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Columna BD',
                'verbose_name_plural': 'Plantillas de Columnas BD',
                'db_table': 'app_generator_db_column_templates',
            },
        ),
        migrations.AlterModelOptions(
            name='dbtable',
            options={'ordering': ['schema_name', 'name'], 'verbose_name': 'Tabla BD', 'verbose_name_plural': 'Tablas BD'},
        ),
        migrations.AlterUniqueTogether(
            name='dbtable',
            unique_together={('schema_name', 'name')},
        ),
        migrations.AddField(
            model_name='dbtable',
            name='table_kind',
            field=models.CharField(choices=[('catalog', 'Catálogo'), ('transaction', 'Transacción')], default='catalog', help_text='Tipo de tabla: Catálogo o Transacción', max_length=20),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='name',
            field=models.CharField(help_text='Nombre técnico (ej: productos)', max_length=100),
        ),
        migrations.RemoveField(
            model_name='dbtable',
            name='application',
        ),
    ]
