# Generated by Django 5.2.5 on 2025-08-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0003_dbcolumntemplate_seed'),
        ('sapy', '0005_dbtable_schema_default_public'),
    ]

    operations = [
    ]
