# Generated by Django 5.2.5 on 2025-08-12 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0007_dbcolumn_position_start_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcolumn',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla/definición base de esta columna (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sapy.dbcolumntemplate'),
        ),
    ]
