# Generated by Django 5.2.5 on 2025-08-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0008_dbcolumn_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('alignment', models.CharField(choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='left', max_length=10)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('visible_in_lists', models.BooleanField(default=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Ancho en px opcional', null=True)),
                ('db_column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_column', to='sapy.dbcolumn')),
            ],
            options={
                'verbose_name': 'Columna UI',
                'verbose_name_plural': 'Columnas UI',
                'db_table': 'app_generator_ui_columns',
            },
        ),
        migrations.CreateModel(
            name='UiField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('input_type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Área de texto'), ('number', 'Número'), ('checkbox', 'Checkbox'), ('date', 'Fecha'), ('datetime-local', 'Fecha/Hora'), ('select', 'Selector')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('step', models.CharField(blank=True, max_length=20)),
                ('min_value', models.CharField(blank=True, max_length=50)),
                ('max_value', models.CharField(blank=True, max_length=50)),
                ('pattern', models.CharField(blank=True, max_length=120)),
                ('placeholder', models.CharField(blank=True, max_length=150)),
                ('options_source', models.CharField(choices=[('none', 'Ninguna'), ('fk', 'Llave foránea')], default='none', max_length=10)),
                ('fk_label_field', models.CharField(blank=True, default='nombre', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('db_column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_field', to='sapy.dbcolumn')),
                ('fk_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sapy.dbtable')),
            ],
            options={
                'verbose_name': 'Campo UI',
                'verbose_name_plural': 'Campos UI',
                'db_table': 'app_generator_ui_fields',
            },
        ),
    ]
