# Generated by Django 5.2.5 on 2025-08-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0010_dbcolumntemplate_more_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicolumn',
            name='is_toggle',
            field=models.BooleanField(default=False, help_text='Renderizar como interruptor en listas'),
        ),
    ]
