# Generated by Django 5.2.5 on 2025-08-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0012_backfill_core_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtable',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
    ]
