# Generated by Django 5.2.5 on 2025-08-12 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0013_dbtable_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre técnico del campo (ej: descripcion, email_usuario)', max_length=100)),
                ('question_text', models.CharField(help_text='Texto de la pregunta que ve el usuario (ej: "Descripción del producto:")', max_length=200)),
                ('help_text', models.CharField(blank=True, help_text='Texto de ayuda opcional', max_length=300)),
                ('input_type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Área de texto'), ('number', 'Número'), ('checkbox', 'Checkbox'), ('radio', 'Radio buttons'), ('select', 'Selector'), ('date', 'Fecha'), ('datetime-local', 'Fecha/Hora'), ('email', 'Email'), ('password', 'Contraseña'), ('file', 'Archivo'), ('hidden', 'Campo oculto')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False, help_text='¿Es obligatorio responder esta pregunta?')),
                ('validation_rule', models.CharField(choices=[('none', 'Ninguna'), ('required', 'Requerido'), ('email', 'Email válido'), ('url', 'URL válida'), ('min_length', 'Longitud mínima'), ('max_length', 'Longitud máxima'), ('pattern', 'Patrón regex'), ('min_value', 'Valor mínimo'), ('max_value', 'Valor máximo')], default='none', max_length=20)),
                ('validation_value', models.CharField(blank=True, help_text='Valor para la validación (ej: longitud min/max, patrón regex)', max_length=100)),
                ('options_source', models.CharField(choices=[('none', 'Ninguna'), ('fk', 'Llave foránea'), ('custom', 'Opciones personalizadas')], default='none', max_length=10)),
                ('options_custom', models.TextField(blank=True, help_text='Opciones separadas por líneas (ej: "Opción 1\\nOpción 2")')),
                ('fk_value_field', models.CharField(blank=True, default='id', help_text='Campo que se guarda como valor', max_length=100)),
                ('fk_label_field', models.CharField(blank=True, default='nombre', help_text='Campo que se muestra al usuario', max_length=100)),
                ('css_class', models.CharField(blank=True, default='col-md-6', help_text='Clases CSS (ej: col-md-6, col-md-12)', max_length=100)),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder para el campo', max_length=150)),
                ('default_value', models.CharField(blank=True, help_text='Valor por defecto', max_length=255)),
                ('order', models.PositiveIntegerField(default=1, help_text='Orden de aparición en el formulario')),
                ('section', models.CharField(blank=True, help_text='Sección del formulario (opcional)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activa esta pregunta?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('db_column', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_question', to='sapy.dbcolumn')),
                ('fk_table', models.ForeignKey(blank=True, help_text='Tabla de origen para opciones FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sapy.dbtable')),
            ],
            options={
                'verbose_name': 'Pregunta de Formulario',
                'verbose_name_plural': 'Preguntas de Formularios',
                'db_table': 'app_generator_form_questions',
                'ordering': ['order', 'name'],
            },
        ),
    ]
