# Generated by Django 5.2.5 on 2025-08-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0015_backfill_form_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbcolumn',
            options={'ordering': ['name'], 'verbose_name': 'Columna BD', 'verbose_name_plural': 'Columnas BD'},
        ),
        migrations.AlterUniqueTogether(
            name='dbcolumn',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dbcolumn',
            name='name',
            field=models.CharField(help_text='Nombre único de la columna (ej: id, nombre, id_familias)', max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='dbcolumn',
            name='on_delete',
        ),
        migrations.RemoveField(
            model_name='dbcolumn',
            name='position',
        ),
        migrations.RemoveField(
            model_name='dbcolumn',
            name='references_table',
        ),
        migrations.RemoveField(
            model_name='dbcolumn',
            name='table',
        ),
        migrations.RemoveField(
            model_name='dbcolumn',
            name='template',
        ),
        migrations.CreateModel(
            name='DbTableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, help_text='Orden de la columna en la tabla (1..N)')),
                ('is_nullable', models.BooleanField(blank=True, help_text='Sobrescribe el valor de DbColumn', null=True)),
                ('is_unique', models.BooleanField(blank=True, help_text='Sobrescribe el valor de DbColumn', null=True)),
                ('is_index', models.BooleanField(blank=True, help_text='Sobrescribe el valor de DbColumn', null=True)),
                ('is_primary_key', models.BooleanField(blank=True, help_text='Sobrescribe el valor de DbColumn', null=True)),
                ('is_auto_increment', models.BooleanField(blank=True, help_text='Sobrescribe el valor de DbColumn', null=True)),
                ('default_value', models.CharField(blank=True, help_text='Sobrescribe el valor por defecto de DbColumn', max_length=255)),
                ('on_delete', models.CharField(choices=[('CASCADE', 'CASCADE'), ('RESTRICT', 'RESTRICT'), ('SET NULL', 'SET NULL'), ('NO ACTION', 'NO ACTION')], default='CASCADE', help_text='Comportamiento ON DELETE para la FK', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_implementations', to='sapy.dbcolumn')),
                ('references_table', models.ForeignKey(blank=True, help_text='Tabla de referencia si es FK', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by_table_columns', to='sapy.dbtable')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='sapy.dbtable')),
            ],
            options={
                'verbose_name': 'Columna de Tabla',
                'verbose_name_plural': 'Columnas de Tablas',
                'db_table': 'app_generator_table_columns',
                'ordering': ['table__name', 'position', 'column__name'],
                'unique_together': {('table', 'column')},
            },
        ),
    ]
