# Generated by Django 5.2.5 on 2025-08-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0016_alter_dbcolumn_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DbColumnTemplate',
        ),
    ]
