# Generated by Django 5.2.5 on 2025-08-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0017_delete_dbcolumntemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el uso de esta tabla en la aplicación')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tables', to='sapy.application')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_applications', to='sapy.dbtable')),
            ],
            options={
                'verbose_name': 'Tabla de Aplicación',
                'verbose_name_plural': 'Tablas de Aplicaciones',
                'db_table': 'app_generator_application_tables',
                'ordering': ['application__name', 'table__name'],
                'unique_together': {('application', 'table')},
            },
        ),
    ]
