# Generated by Django 5.2.5 on 2025-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0022_update_width_fraction_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalformfieldoverride',
            name='width_fraction',
            field=models.CharField(choices=[('1-1', '1/1 (100%)'), ('1-2', '1/2 (50%)'), ('1-3', '1/3 (33%)'), ('2-3', '2/3 (67%)'), ('1-4', '1/4 (25%)'), ('3-4', '3/4 (75%)'), ('1-6', '1/6 (17%)'), ('5-6', '5/6 (83%)')], default='1-1', max_length=10),
        ),
    ]
