# Generated by Django 5.2.5 on 2025-08-13 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0023_update_width_fraction_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el uso de esta página en la aplicación')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pages', to='sapy.application')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_applications', to='sapy.page')),
            ],
            options={
                'verbose_name': 'Página de Aplicación',
                'verbose_name_plural': 'Páginas de Aplicaciones',
                'db_table': 'app_generator_application_pages',
                'ordering': ['application__name', 'page__slug'],
                'unique_together': {('application', 'page')},
            },
        ),
    ]
