# Generated by Django 5.2.5 on 2025-08-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0024_applicationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Identificador único en minúsculas (ej: usuarios)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Título visible en el menú', max_length=150)),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: bi bi-people, fas fa-user)', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'db_table': 'app_generator_menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, help_text='Etiqueta de sección para agrupar opciones', max_length=100)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_pages', to='sapy.menu')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_assignments', to='sapy.page')),
            ],
            options={
                'verbose_name': 'Página de Menú',
                'verbose_name_plural': 'Páginas de Menú',
                'db_table': 'app_generator_menu_pages',
                'ordering': ['menu__name', 'section', 'order_index'],
                'unique_together': {('menu', 'page')},
            },
        ),
    ]
