# Generated by Django 5.2.5 on 2025-08-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0025_menu_menupage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('bi', 'Bootstrap Icons'), ('fa', 'Font Awesome Free')], default='bi', max_length=10)),
                ('class_name', models.CharField(help_text='Clase CSS completa, ej: "bi bi-people" o "fas fa-user"', max_length=120, unique=True)),
                ('label', models.CharField(blank=True, help_text='Etiqueta legible (opcional)', max_length=150)),
                ('tags', models.TextField(blank=True, help_text='Palabras clave separadas por espacio/coma (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ícono',
                'verbose_name_plural': 'Íconos',
                'db_table': 'app_generator_icons',
                'ordering': ['provider', 'class_name'],
            },
        ),
    ]
