# Generated by Django 5.2.5 on 2025-08-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0026_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='library',
            field=models.CharField(blank=True, help_text='bootstrap-icons | fontawesome6', max_length=32),
        ),
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='icon',
            name='style',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='icon',
            name='unicode',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='icon',
            name='version',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
