# Generated by Django 5.2.5 on 2025-08-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0027_icon_library_icon_name_icon_style_icon_unicode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_menus', to='sapy.application')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_applications', to='sapy.menu')),
            ],
            options={
                'verbose_name': 'Menú de Aplicación',
                'verbose_name_plural': 'Menús de Aplicaciones',
                'db_table': 'app_generator_application_menus',
                'ordering': ['application__name', 'menu__name'],
                'unique_together': {('application', 'menu')},
            },
        ),
    ]
