# Generated by Django 5.2.5 on 2025-08-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0028_applicationmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationPage',
        ),
    ]
