# Generated by Django 5.2.5 on 2025-08-13 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0029_delete_applicationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Identificador único en minúsculas, ej: vendedor', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Nombre visible, ej: Vendedor', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'app_generator_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='sapy.menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='sapy.role')),
            ],
            options={
                'verbose_name': 'Menú por Rol',
                'verbose_name_plural': 'Menús por Rol',
                'db_table': 'app_generator_role_menus',
                'ordering': ['role__name', 'menu__name'],
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
