# Generated by Django 5.2.5 on 2025-08-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapy', '0030_role_rolemenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'En Diseño'), ('generating', 'Generando'), ('generated', 'Generada'), ('installing', 'Instalando'), ('reinstalling', 'Reinstalando'), ('deployed', 'Desplegada'), ('error', 'Error'), ('maintenance', 'Mantenimiento')], default='draft', max_length=20),
        ),
    ]
